### PR TITLE
Email authentication bug fixed with redirecting it to a Httpresponse …

### PR DESCRIPTION
**Pull request by YashRaj1506**
…page on succesful OTP verification

## Fixes

Fixes #[issue number] by @[issue author]

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update
index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main` or `master`).
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no
      visible errors.

[best_practices]: https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

### CODE REVIEW

**Comment by YashRaj1506** [comment]
When the Verification code has been verified it currently redirects it to a HttpResponse page to show verification has occurred successfully. It can be later used to redirect it to the Dashboard.

**Comment by SAMAD101** [comment]
Why add those extra lines and cut down the standard spacing inside those lists and dicts in `settings.py` ? It was fine as it was before

**Comment by SAMAD101** [comment]
rest looks fine. Just refactor `verify,html` , I'll install `pre-commit` for linting

**Comment by YashRaj1506** [comment]
Okay got it, working on it.

**Pull request merged**
